'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {fetchApi,errorMessage} from '@/lib/research'
import {Panel,ErrorBox,field,button} from '@/components/research-ui'
export default function NewProject(){
 const router=useRouter(); const [name,setName]=useState(''); const [question,setQuestion]=useState(''); const [description,setDescription]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(from&&to&&from>to)throw new Error('Start date must be on or before end date.');const p=await fetchApi<{id:string}>('/projects',{method:'POST',body:JSON.stringify({name,research_question:question,description,date_from:from||null,date_to:to||null,domain:'general'})});router.push(`/projects/${p.id}/collections`)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <div className="mx-auto max-w-3xl space-y-6 p-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">New research project</p><h1 className="mt-2 text-2xl font-bold">What do you want to understand?</h1><p className="mt-2 text-text-muted">Study conversations about public transport, education, climate, technology, or another topic.</p></div><ErrorBox message={error}/><Panel><form onSubmit={create} className="space-y-5"><label className="block text-sm font-medium">Project title<input className={field+' mt-2'} required maxLength={255} value={name} onChange={e=>setName(e.target.value)} placeholder="Public attitudes toward urban cycling"/></label><label className="block text-sm font-medium">Research question<textarea className={field+' mt-2'} required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="How do people describe barriers to cycling in their city?"/></label><label className="block text-sm font-medium">Description and research context<textarea className={field+' mt-2'} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Start date (optional)<input type="date" className={field+' mt-2'} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">End date (optional)<input type="date" className={field+' mt-2'} value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></div><p className="text-xs text-text-muted">Without dates, existing provider defaults apply. Dates do not guarantee complete historical coverage. Creating a project does not spend provider credits.</p><button className={button} disabled={busy}>{busy?'Creating...':'Create project and choose sources'}</button></form></Panel></div>
}
