'use client'
import {useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import Link from 'next/link'
import {fetchApi,dateLabel,errorMessage,Run} from '@/lib/research'
import {Project} from '@/lib/api'
import {Panel,ErrorBox,button,secondary} from '@/components/research-ui'
export default function Overview(){const {id}=useParams<{id:string}>();const [p,setP]=useState<Project>();const [runs,setRuns]=useState<Run[]>([]);const [error,setError]=useState('')
 useEffect(()=>{Promise.all([fetchApi<Project>(`/projects/${id}`),fetchApi<Run[]>(`/projects/${id}/jobs`)]).then(([p,r])=>{setP(p);setRuns(r)}).catch(e=>setError(errorMessage(e)))},[id]);
 return <div className="mx-auto max-w-6xl space-y-6 p-6"><ErrorBox message={error}/>{p?<><div><p className="text-xs uppercase tracking-wider text-primary">Research overview</p><h1 className="mt-2 text-3xl font-bold">{p.name}</h1><p className="mt-3 text-lg">{p.research_question||p.description||'Add your research context when creating a project.'}</p><p className="mt-2 text-text-muted">{p.description}</p></div><div className="flex flex-wrap gap-3"><Link className={button} href={`/projects/${id}/results`}>View results</Link><Link className={secondary} href={`/projects/${id}/collections`}>Collect more</Link></div><div className="grid gap-4 sm:grid-cols-3"><Panel><p className="text-sm text-text-muted">Unique posts in project</p><p className="mt-2 text-3xl font-bold">{p.post_count.toLocaleString()}</p><p className="mt-2 text-xs text-text-muted">Includes previews and excluded posts</p></Panel><Panel><p className="text-sm text-text-muted">Collection activity</p><p className="mt-2 text-3xl font-bold">{runs.length}</p><p className="mt-2 text-xs text-text-muted">Previews and full runs, with original settings</p></Panel><Panel><p className="text-sm text-text-muted">Latest run</p><p className="mt-2 font-semibold">{runs[0]?.status.replaceAll('_',' ')||'No collections yet'}</p><p className="mt-2 text-xs text-text-muted">{runs[0]?dateLabel(runs[0].created_at):'Start with a small search preview.'}</p></Panel></div><Panel><h2 className="font-semibold">Requested research period</h2><p className="mt-2 text-sm">{p.date_from||'Provider default start'} to {p.date_to||'Provider default end'}</p><p className="mt-2 text-sm text-text-muted">Each run keeps its own dates. Search results are not a representative sample, and selected dates do not establish complete coverage.</p></Panel></>:!error&&<p>Loading project...</p>}</div>}
