'use client'
import {useCallback,useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import Link from 'next/link'
import {fetchApi,Run,SourceInfo,active,dateLabel,errorMessage,label} from '@/lib/research'
import { PlatformBadge } from '@/components/platform-badge'
import { CollectionHistory } from '@/components/collection-history'
import {Project} from '@/lib/api'
import {Panel,ErrorBox,field,button,secondary} from '@/components/research-ui'
export default function Collections(){
 const {id}=useParams<{id:string}>();const [runs,setRuns]=useState<Run[]>([]);const [sources,setSources]=useState<SourceInfo>();const [query,setQuery]=useState('');const [selected,setSelected]=useState(['instagram','tiktok','facebook']);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [target,setTarget]=useState(500);const [cap,setCap]=useState(8);const [primary,setPrimary]=useState(20);const [requests,setRequests]=useState(20);const [pull,setPull]=useState<string>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const reload=useCallback(async()=>{setRuns(await fetchApi<Run[]>(`/projects/${id}/jobs`))},[id]);
 useEffect(()=>{Promise.all([fetchApi<Project>(`/projects/${id}`),fetchApi<SourceInfo>('/sources'),fetchApi<Run[]>(`/projects/${id}/jobs`)]).then(([p,s,r])=>{setSources(s);setRuns(r);setQuery(p.boolean_query||'');setFrom(p.date_from?.slice(0,10)||'');setTo(p.date_to?.slice(0,10)||'')}).catch(e=>setError(errorMessage(e)))},[id]);
 useEffect(()=>{if(!runs.some(r=>active(r.status)))return;const timer=setInterval(()=>reload().catch(e=>setError(errorMessage(e))),2500);return()=>clearInterval(timer)},[runs,reload]);
 const current=runs.find(r=>r.pull_id===pull);const inFlight=runs.some(r=>r.pull_id===pull&&active(r.status));const fullExists=runs.some(r=>r.pull_id===pull&&r.mode==='collection');
 async function start(mode:'preview'|'collection'){
  setBusy(true);setError('');setNotice('');try{
   if(!query.trim()||!selected.length)throw new Error('Enter a search query and select at least one source.');
   if(from&&to&&from>to)throw new Error('Start date must be on or before end date.');
   const run=await fetchApi<Run>(`/projects/${id}/jobs`,{method:'POST',body:JSON.stringify({name:`${mode==='preview'?'Preview':'Collection'}: ${query.slice(0,80)}`,query,platforms:selected,date_from:from?from+'T00:00:00Z':null,date_to:to?to+'T23:59:59.999999Z':null,requested_post_count:target,pull_id:pull||null,mode,comparison_limit:cap,primary_credit_limit:primary,request_limit:requests})});
   setPull(run.pull_id);setNotice(active(run.status)?'Run queued. Progress will update below.':run.status==='failed'?'Run could not start. See the recorded error below.':`Reused preview collected ${dateLabel(run.created_at)}; no additional requests.`);await reload()
  }catch(e){setError(errorMessage(e))}finally{setBusy(false)}
 }
 function resume(r:Run){setPull(r.pull_id);setQuery(r.query_versions[0]?.boolean_query||'');setSelected(r.platforms);setFrom(r.date_from?.slice(0,10)||'');setTo(r.date_to?.slice(0,10)||'');setTarget(r.requested_post_count);setCap(r.usage.comparison_limit);setRequests(r.usage.request_limit_per_platform);setPrimary(Object.entries(r.usage.platforms).find(([p])=>p==='tiktok'||p==='facebook')?.[1].credit_limit||20);setNotice('Continuing the existing pull. Previous usage remains charged.')}
 async function cancel(run:Run){try{await fetchApi(`/projects/${id}/jobs/${run.id}/cancel`,{method:'POST'});await reload()}catch(e){setError(errorMessage(e))}}
 return <div className="mx-auto max-w-6xl space-y-6 p-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Collections</h1><p className="mt-2 text-sm text-text-muted">Search across platforms and collect the conversations that matter.</p></div><button className={secondary} disabled={busy||inFlight} onClick={()=>{setPull(undefined);setNotice('Ready for a new query pull.')}}>Start a new pull</button></div><ErrorBox message={error}/>{notice&&<p role="status" className="rounded-lg bg-primary/10 p-3 text-sm text-primary">{notice}</p>}
 <Panel><div className="space-y-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{pull?'Continue query pull':'New query pull'}</h2>{pull&&<span className="break-all text-xs text-text-muted">Current pull / {pull.slice(0,8)}</span>}</div><label className="block text-sm font-medium">Search terms<textarea className={field+' mt-2'} rows={3} maxLength={200} placeholder='"bike lane" OR "cycling infrastructure"' value={query} onChange={e=>setQuery(e.target.value)} disabled={inFlight||fullExists}/></label><p className="text-xs text-text-muted">Use AND, OR, and quotes to refine your search.</p>
 <div className="grid gap-3 sm:grid-cols-3">{sources?.sources.map(s=><label key={s.platform} className="flex gap-3 rounded-lg border border-border p-3 text-sm"><input type="checkbox" checked={selected.includes(s.platform)} disabled={!!pull||busy} onChange={e=>setSelected(v=>e.target.checked?[...v,s.platform]:v.filter(p=>p!==s.platform))}/><span><PlatformBadge platform={s.platform}/><span className="mt-1 block text-xs text-text-muted">{s.configured?'Ready to collect':'Unavailable - missing provider key'}</span></span></label>)}</div>
 <div className="grid gap-4 sm:grid-cols-3"><label className="text-sm">Start date (optional)<input className={field+' mt-2'} type="date" value={from} onChange={e=>setFrom(e.target.value)} disabled={inFlight||fullExists}/></label><label className="text-sm">End date (optional)<input className={field+' mt-2'} type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} disabled={inFlight||fullExists}/></label><label className="text-sm">Total post target (100-5,000)<input className={field+' mt-2'} type="number" min={100} max={5000} value={target} onChange={e=>setTarget(Number(e.target.value))} disabled={inFlight||fullExists}/></label></div>
 <details className="rounded-lg bg-background p-4"><summary className="cursor-pointer text-sm font-medium">Collection safeguards</summary><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm">Shared comparison credits<input type="number" min={5} max={8} className={field+' mt-2'} value={cap} onChange={e=>setCap(Number(e.target.value))} disabled={!!pull}/></label><label className="text-sm">Credits per primary SociaVault source<input type="number" min={1} max={100} className={field+' mt-2'} value={primary} onChange={e=>setPrimary(Number(e.target.value))} disabled={!!pull}/></label><label className="text-sm">Request attempts per source<input type="number" min={1} max={100} className={field+' mt-2'} value={requests} onChange={e=>setRequests(Number(e.target.value))} disabled={!!pull}/></label></div><p className="mt-3 text-xs text-text-muted">X, Reddit, and YouTube share {cap} credits across every preview and full collection in this pull. Selected comparison sources receive equal allocations; remainder order: X, Reddit, YouTube. Unused credit is not transferred. Instagram has SDK-operation limits; its credit cost is unknown. Allowances are fixed when the pull starts.</p></details>
 <details className="text-xs text-text-muted"><summary className="cursor-pointer font-medium">Search coverage & provider limits</summary><p className="mt-2 leading-relaxed">Previews aim for up to 20 posts per source. Unchanged previews and SociaVault pages are reused for 15 minutes. Dates do not guarantee complete coverage; the target may not be reached. Instagram has a maximum of 300 results per search and may require a new search for full collection.</p></details>
 {current&&<Budget run={current}/>}
 <div className="flex flex-wrap gap-3"><button className={secondary} disabled={busy||inFlight||fullExists} onClick={()=>start('preview')}>{busy?'Submitting...':'Search preview'}</button><button className={button} disabled={busy||inFlight||fullExists||target<100||target>5000} onClick={()=>start('collection')}>Collect up to {target.toLocaleString()} posts</button></div><p className="text-xs text-text-muted">{sources?.account_limit_warning}</p></div></Panel>
 <CollectionHistory runs={runs} projectId={id} busy={busy} inFlight={inFlight} resume={resume} cancel={cancel} renderBudget={run=><Budget run={run}/>}/>

 </div>
}
function Budget({run}:{run:Run}){const u=run.usage;if(!u?.platforms)return null;return <div className="rounded-lg bg-background p-4"><p className="text-sm font-medium">Shared comparison allowance: {u.comparison_remaining} of {u.comparison_limit} credits remaining</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{Object.entries(u.platforms).map(([p,v])=><div key={p} className="text-xs"><p className="font-semibold">{label(p)}: {v.requests}/{u.request_limit_per_platform} attempts</p><p className="mt-1 text-text-muted">{v.credits_bounded?`${v.charged_allowance}/${v.credit_limit} credits debited; ${v.reported} reported, ${v.estimated} estimated, ${v.reserved} reserved`:'Credit usage unknown; SDK operations only'}</p>{v.unknown_requests>0&&<p className="mt-1 text-text-muted">{v.unknown_requests} pending or uncertain charges retained</p>}</div>)}</div><p className="mt-3 text-xs text-text-muted">Usage is cumulative for the pull, including abandoned previews and billable or potentially billable retries.</p></div>}
