'use client'
import {useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import {fetchApi,errorMessage,dateLabel,platforms,label} from '@/lib/research'
import {Panel,ErrorBox,field,button,secondary} from '@/components/research-ui'
interface Export {id:string;status:string;created_at:string;row_count:number;filters:{scope?:string};download_url?:string;error_message?:string}
export default function Exports(){const {id}=useParams<{id:string}>();const [jobs,setJobs]=useState<Export[]>([]);const [scope,setScope]=useState('included');const [source,setSource]=useState('');const [search,setSearch]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){setJobs(await fetchApi<Export[]>(`/projects/${id}/exports`))}useEffect(()=>{load().catch(e=>setError(errorMessage(e)))},[id]);
 async function create(){setBusy(true);setError('');try{const e=await fetchApi<Export>(`/projects/${id}/exports`,{method:'POST',body:JSON.stringify({format:'csv',scope,platform:source?[source]:null,search:search||null,date_from:from?from+'T00:00:00Z':null,date_to:to?to+'T23:59:59.999999Z':null})});if(e.status==='failed')throw new Error(e.error_message||'Export failed. Check the API logs using the export ID.');await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function download(e:Export){try{const response=await fetch(e.download_url!,{headers:{Authorization:`Bearer ${localStorage.getItem('socialscope_token')}`}});if(!response.ok)throw new Error('Download failed. Sign in again or generate a new export.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`socialscope-${e.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(errorMessage(e))}}
 return <div className="mx-auto max-w-5xl space-y-6 p-6"><div><h1 className="text-2xl font-bold">Export your research dataset</h1><p className="mt-2 text-sm text-text-muted">One row per unique project post, with provider, collection time, run/query/date provenance and known limitations.</p></div><ErrorBox message={error}/><Panel><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Scope<select className={field+' mt-2'} value={scope} onChange={e=>setScope(e.target.value)}><option value="included">Included in analysis</option><option value="excluded">Excluded from analysis</option><option value="all">All collected posts</option></select></label><label className="text-sm">Source<select className={field+' mt-2'} value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{platforms.map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label><label className="text-sm">Published from<input type="date" className={field+' mt-2'} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Published through<input type="date" className={field+' mt-2'} value={to} onChange={e=>setTo(e.target.value)}/></label><label className="text-sm sm:col-span-2">Text filter<input className={field+' mt-2'} value={search} onChange={e=>setSearch(e.target.value)}/></label></div><button className={button+' mt-5'} disabled={busy} onClick={create}>{busy?'Preparing CSV...':'Generate CSV'}</button><p className="mt-3 text-xs text-text-muted">Collection context is a JSON field containing every run that encountered each post. Preview posts are part of the project dataset. Exclusion is preserved in the CSV.</p></Panel><h2 className="text-lg font-semibold">Export history</h2>{jobs.length?jobs.map(e=><Panel key={e.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{e.row_count||0} posts / {e.filters.scope||'included'} / {e.status}</p><p className="mt-1 text-xs text-text-muted">{dateLabel(e.created_at)} / {e.id}</p></div>{e.download_url&&<button className={secondary} onClick={()=>download(e)}>Download CSV</button>}</div>{e.error_message&&<p className="mt-3 text-sm text-red-700">{e.error_message}</p>}</Panel>):<Panel><p className="text-sm text-text-muted">No exports yet. Choose the dataset scope above and generate a CSV.</p></Panel>}</div>}
